'use client';
import {createContext,useContext,useEffect,useState,ReactNode} from 'react';
import {ShoppingBag,X,MagnifyingGlass,Heart,List,ArrowUpRight,Minus,Plus} from '@phosphor-icons/react';
import {products,money,Product} from '@/lib/products';
const C=createContext<any>(null); export function StoreProvider({children}:{children:ReactNode}){const [cart,setCart]=useState<any[]>([]);useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('rtb-cart')||'[]'))}catch{}},[]);useEffect(()=>{localStorage.setItem('rtb-cart',JSON.stringify(cart))},[cart]);const add=(p:Product)=>setCart((c:any[])=>{const x=c.find(i=>i.product.id===p.id);return x?c.map(i=>i.product.id===p.id?{...i,qty:i.qty+1}:i):[...c,{product:p,qty:1}]});const remove=(id:string)=>setCart(c=>c.filter(i=>i.product.id!==id));const change=(id:string,d:number)=>setCart(c=>c.map(i=>i.product.id===id?{...i,qty:Math.max(1,i.qty+d)}:i));return <C.Provider value={{cart,add,remove,change}}>{children}</C.Provider>}; export const useStore=()=>useContext(C);
export function Header(){const [open,setOpen]=useState(false);const [search,setSearch]=useState(false);const {cart}=useStore();return <><div className="bg-[#1f4d3b] text-white text-center text-[11px] tracking-[.16em] py-2">COMPLIMENTARY DELIVERY ON ORDERS OVER ₦150,000</div><header className="sticky top-0 z-40 border-b border-black/10 bg-[#f7f7f5]/95 backdrop-blur"><div className="container h-[72px] flex items-center justify-between gap-6"><button className="lg:hidden" onClick={()=>setOpen(true)}><List size={24}/></button><a href="/" className="text-2xl font-black tracking-[-.08em]">RTB</a><nav className="hidden lg:flex items-center gap-8 text-sm"><a href="/shop">Shop</a><a href="/collections/new-season">Collections</a><a href="/about">About</a><a href="/contact">Contact</a></nav><div className="flex items-center gap-4"><button onClick={()=>setSearch(true)}><MagnifyingGlass size={21}/></button><button className="hidden sm:block"><Heart size={21}/></button><a href="/cart" className="relative"><ShoppingBag size={21}/>{cart.length>0&&<span className="absolute -right-2 -top-2 bg-[#1f4d3b] text-white text-[9px] w-4 h-4 rounded-full grid place-items-center">{cart.reduce((a:any,i:any)=>a+i.qty,0)}</span>}</a></div></div></header>{open&&<div className="fixed inset-0 z-50 bg-black/30 lg:hidden"><aside className="w-[88%] max-w-sm h-full bg-[#f7f7f5] p-7"><div className="flex justify-between"><span className="text-2xl font-black tracking-[-.08em]">RTB</span><button onClick={()=>setOpen(false)}><X size={24}/></button></div><nav className="mt-14 grid gap-7 text-2xl"><a href="/shop">Shop</a><a href="/collections/new-season">Collections</a><a href="/about">About</a><a href="/contact">Contact</a></nav></aside></div>}{search&&<div className="fixed inset-0 z-50 bg-[#f7f7f5]"><div className="container pt-7"><div className="flex justify-between"><span className="text-2xl font-black tracking-[-.08em]">RTB</span><button onClick={()=>setSearch(false)}><X size={25}/></button></div><div className="mt-20 border-b border-black/30 flex items-center gap-4"><MagnifyingGlass size={24}/><input autoFocus placeholder="Search RTB" className="bg-transparent outline-none text-4xl w-full py-5"/></div><p className="mt-6 text-sm text-black/50">Search our collection</p></div></div>}</>}

export function Footer(){return <footer className="border-t border-black/10 mt-24"><div className="container py-16 grid md:grid-cols-4 gap-12"><div><div className="text-3xl font-black tracking-[-.08em]">RTB</div><p className="text-sm text-black/55 mt-4 max-w-xs">Considered everyday pieces designed around simplicity, confidence and effortless style.</p></div><div><b className="text-sm">SHOP</b><div className="grid gap-3 mt-5 text-sm text-black/60"><a href="/shop">All products</a><a href="/collections/new-season">New arrivals</a><a href="/shop?category=Abayas">Abayas</a><a href="/shop?category=Hijabs">Hijabs</a></div></div><div><b className="text-sm">HELP</b><div className="grid gap-3 mt-5 text-sm text-black/60"><a href="/contact">Contact</a><a href="/size-guide">Size guide</a><a href="/shipping-returns">Shipping & returns</a></div></div><div><b className="text-sm">STAY CONNECTED</b><p className="text-sm text-black/55 mt-5">New drops, collections and RTB updates.</p><div className="mt-5 flex border-b border-black/30"><input placeholder="Email address" className="bg-transparent py-3 outline-none flex-1 text-sm"/><button><ArrowUpRight size={20}/></button></div></div></div><div className="container border-t border-black/10 py-6 text-xs text-black/45 flex justify-between"><span>© 2026 RTB</span><span>Made for everyday.</span></div></footer>}

export function ProductCard({p}:{p:Product}){const {add}=useStore();return <article className="group"><a href={'/product/'+p.slug} className="block overflow-hidden bg-[#e9e9e4] aspect-[3/4]"><img src={p.images[0]} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-[1.035]" alt={p.name}/></a><div className="pt-4 flex justify-between gap-3"><div><a href={'/product/'+p.slug} className="text-sm font-medium">{p.name}</a><p className="text-sm text-black/50 mt-1">{money(p.price)}</p><div className="flex gap-1.5 mt-3">{p.colors.map(c=><span key={c} title={c} className="w-3 h-3 rounded-full border border-black/15" style={{background:c==='Black'?'#111':c==='Olive'?'#66705a':'#c9b89d'}}/>)}</div></div><button aria-label="Add to cart" onClick={()=>add(p)} className="shrink-0 border border-black/15 w-9 h-9 rounded-full grid place-items-center hover:bg-black hover:text-white transition"><Plus size={17}/></button></div></article>}

export function ProductGrid({items=products}:{items?:Product[]}){return <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-x-4 md:gap-x-6 gap-y-12">{items.map(p=><ProductCard key={p.id} p={p}/>)}</div>}